name: Build & Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build_and_test:
    runs-on: macos-15
    steps:
    - uses: actions/checkout@v4
    
    - name: Select Xcode
      run: sudo xcode-select -s /Applications/Xcode_16.app/Contents/Developer
      
    - name: Clean & Build
      env:
        MACOSX_DEPLOYMENT_TARGET: "14.0"
      run: |
        xcodebuild build \
          -project WordWise.xcodeproj \
          -scheme WordWise \
          -destination 'platform=macOS,arch=arm64' \
          -configuration Debug
      
    - name: Run Tests
      continue-on-error: true
      env:
        MACOSX_DEPLOYMENT_TARGET: "14.0"
      run: |
        xcodebuild test \
          -project WordWise.xcodeproj \
          -scheme WordWiseTests \
          -destination 'platform=macOS,arch=arm64' \
          -configuration Debug
